# -*- coding: utf-8 -*-
"""project 112

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vvrXIBHUAU0FmK04wBg_Fa-adrhLvl7f
"""

from google.colab import files 
files.upload()

import csv
import pandas as pd
import plotly.express as px

df = pd.read_csv("savings_data.csv")
fig = px.scatter(df, y="quant_saved", color = "female")
fig.show()

import plotly.graph_objects as go

with open("savings_data.csv", newline = "") as f:
  reader = csv.reader(f)
  savingsdata = list(reader)
savingsdata.pop(0)
highschool = len(savingsdata)
wealthy = 0
female = 0

for data in savingsdata:
  if int(data[3]) == 1:
    highschool += 1
  else:
    female +=1

fig = go.Figure(go.Bar(x=["Reminded", "Not Reminded"], y=[wealthy,female ]))
fig.show()